# _config.yml 파일
title: "LEE's Portfolio"
description: "A personal portfolio and blog using Jekyll"
baseurl: "/Portfolio/"
url: "https://yeonwoo-code.github.io/" # 실제로 사이트를 배포할 도메인으로 수정


author:
  name: "Yeonwoo"
  email: "flee.yw64@gmail.com"
  github: "https://github.com/Yeonwoo-code"
  

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
